version: '3.7'

#
# see vars/e211_jupyterhub.yml for
# hub_service_name, dockerhub_id, container_version, hub_domain
#
services:

  {{ e211_hub_service_name }}:
    build: {{ e211_hub_service_name }}_image
    image: {{ dockerhub_id }}/{{ e211_hub_service_name }}:{{ e211_container_version }}
    container_name: {{ e211_hub_service_name }}_{{ e211_container_version }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JHUB_OAUTH_CALLBACK_URL
      - JHUB_OAUTH_CLIENT_ID
      - JHUB_OAUTH_CLIENT_SECRET
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jhub.rule=Host(`{{ e211_hub_domain }}`)"
      - traefik.http.routers.jhub.tls=true
      - traefik.http.routers.jhub.tls.certresolver=lets-encrypt
      - "traefik.http.routers.jhub.service={{e211_hub_service_name }}"
      - "traefik.http.services.{{ e211_hub_service_name }}.loadbalancer.server.port=8000"
    restart: on-failure
    networks:
      - {{ network_name }}


networks:
  {{ network_name }}:
    external: true
